name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout source
        uses: actions/checkout@v3

      # Setup GCC
      - name: Install GCC
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++ make

      # Install GoogleTest
      - name: Install GoogleTest
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtest-dev
          cd /usr/src/gtest
          sudo cmake .
          sudo make
          sudo cp *.a /usr/local/lib

      # Run Make to build the project
      - name: Build with Makefile
        run: |
          make

      # Run tests (adjust if you have a specific testing framework)
      - name: Run tests
        run: |
          ./my_program --gtest_output=xml:test_results.xml

      # Run Cppcheck
      - name: Run Cppcheck
        run: |
          cppcheck --enable=all --inconclusive --error-exitcode=1 src/
