name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: cmake/setup-cmake@v3  # Correct action for CMake setup

    - name: Set up GCC
      uses: gcc-actions/setup-gcc@v2  # Correct action for GCC setup

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential cppcheck

    - name: Build the project
      run: |
        mkdir -p build
        cd build
        cmake ..
        make

    - name: Run tests
      run: |
        cd build
        ./test  # Assuming your test executable is named `test`

    - name: Static analysis with cppcheck
      run: cppcheck --enable=all --inconclusive --std=c99 src

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build/

    - name: Clean up
      run: make clean
