name: C/C++ CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true  # Ensure submodules are cloned

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ make cppcheck  # Install required tools including Cppcheck

    - name: Build Google Test from submodule
      run: |
        cd external/googletest
        cmake .
        make

    - name: Run static code analysis with Cppcheck
      run: |
        make cppcheck  # Run Cppcheck as part of the pipeline

    - name: Build and run tests
      run: |
        make all  # Build the main program
        make run_tests  # Run the tests using Google Test

    - name: Upload test results (optional)
      if: always()
      run: |
        # Optionally, upload results or logs for further analysis
        echo "Test results uploaded."

    - name: Clean up
      run: |
        make clean  # Clean up build artifacts
