name: CCI/CD Pipeline with Cppcheck and Google Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Initialize and update the Google Test submodule
    - name: Initialize and update submodules
      run: |
        git submodule update --init --recursive

    # Install dependencies: Cppcheck, build-essential, cmake, googletest
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake cppcheck libgtest-dev

    # Build the project using the Makefile
    - name: Build project
      run: |
        make

    # Run Cppcheck for static analysis
    - name: Run Cppcheck
      run: |
        make cppcheck

    # Run tests with Google Test
    - name: Run Tests
      run: |
        make run_tests
