name: C Program CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Install dependencies
    - name: Install GCC and Make
      run: sudo apt-get update && sudo apt-get install -y build-essential

    # Step 3: Install cppcheck
    - name: Install cppcheck
      run: sudo apt-get install -y cppcheck

    # Step 4: Run cppcheck and save results
    - name: Static Code Analysis with cppcheck
      run: cppcheck --enable=all --inconclusive --std=c99 src/ --xml 2> cppcheck-results.xml

    # Step 5: Upload cppcheck results as an artifact
    - name: Upload cppcheck results
      uses: actions/upload-artifact@v3
      with:
        name: cppcheck-results
        path: cppcheck-results.xml

    # Step 6: Build the program
    - name: Build program
      run: make

    # Step 7: Run the program
    - name: Run program
      run: ./sensor_program

    # Step 8: Clean build
    - name: Clean build
      run: make clean
