name: C Program CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Install dependencies
    - name: Install GCC and Make
      run: sudo apt-get update && sudo apt-get install -y build-essential

    # Step 3: Build the program
    - name: Build program
      run: make

    # Step 4: Run the program
    - name: Run program
      run: ./sensor_program

    # Step 5: Clean up build files
    - name: Clean build
      run: make clean
