name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cppcheck cmake g++ gcc

    - name: Run cppcheck
      run: |
        make cppcheck

    - name: Build application
      run: |
        make all

    - name: Install GoogleTest
      run: |
        mkdir -p googletest/build
        cd googletest
        git clone https://github.com/google/googletest.git .
        mkdir -p build
        cd build
        cmake ..
        make
        sudo make install

    - name: Build tests
      run: |
        make test

    - name: Run tests
      run: |
        ./bin/tests

    - name: Upload artifacts
      if: ${{ failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: logs
        path: bin/tests
