name: C CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true  # Initialize and update submodules

      - name: Set up CMake
        uses: actions/setup-cmake@v2

      - name: Set up GCC
        uses: gcc-actions/setup-gcc@v2
        with:
          version: '13.3.0'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake cppcheck googletest libgtest-dev

      - name: Install GoogleTest submodule
        run: |
          git submodule update --init --recursive  # Ensure submodules are initialized

      - name: Run cppcheck
        run: |
          make cppcheck  # Run cppcheck for static analysis

      - name: Build and test with Makefile
        run: |
          make all        # Build the project
          make tests      # Run tests

      - name: Upload Test Results
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: $(BUILD_DIR)/test-output
