name: C Program CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-analyze:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Install dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev cppcheck
        cd /usr/src/gtest
        sudo cmake .
        sudo make
        sudo cp *.a /usr/lib

    # Step 3: Run Cppcheck (Static Analysis)
    - name: Static Code Analysis with Cppcheck
      run: |
        cppcheck --enable=all --inconclusive --std=c99 src/ --xml 2> cppcheck-results.xml
    - name: Upload Cppcheck Results
      uses: actions/upload-artifact@v3
      with:
        name: cppcheck-results
        path: cppcheck-results.xml

    # Step 4: Build the program
    - name: Build the program
      run: make

    # Step 5: Run the program
    - name: Run the program
      run: ./sensor_program

    # Step 6: Build and Run Google Tests
    - name: Build and Run Tests
      run: make test

    # Step 7: Clean up build artifacts
    - name: Clean build artifacts
      run: make clean
