name: C Program CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Install dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev
        cd /usr/src/gtest
        sudo cmake .
        sudo make
        sudo cp *.a /usr/lib

    # Step 3: Run cppcheck
    - name: Static Code Analysis with cppcheck
      run: cppcheck --enable=all --inconclusive --std=c99 src/

    # Step 4: Build program
    - name: Build program
      run: make

    # Step 5: Run program
    - name: Run program
      run: ./sensor_program

    # Step 6: Build and run tests
    - name: Build and run tests
      run: make test

    # Step 7: Clean build
    - name: Clean build
      run: make clean
