name: C/C++ CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up GCC
      uses: gcc-actions/setup-gcc@v1
      with:
        version: '13'
    
    - name: Set up CMake
      uses: actions/setup-cmake@v3
      with:
        cmake-version: '3.24'
    
    - name: Install cppcheck
      run: |
        sudo apt update
        sudo apt install -y cppcheck
    
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y googletest libgtest-dev cmake make g++ gcc
    
    - name: Build project
      run: |
        make

    - name: Run cppcheck
      run: |
        make cppcheck
    
    - name: Run tests with Google Test
      run: |
        ./my_program
